export enum VerificationType {
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
    PHONE_VERIFICATION= "PHONE_VERIFICATION",
    PASSWORD_RESET = "PASSWORD_RESET",
    TWO_FACTOR_AUTH ="TWO_FACTOR_AUTH" 
}