name: Deploy Next.js to Cloudflare Pages

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Load Environment Variables
        env: 
          NEXT_PUBLIC_API_ENDPOINT: ${{secrets.NEXT_PUBLIC_API_ENDPOINT}}
        run: |
          for VAR in $(printend | grep NEXT_PUBLIC_); do 
            echo "$VAR" >> $GITHUB_ENV
          done

      - name: Build Next.js
        run: rm -rf .next && npm run build && run -rf ./.next/cache/wepack


      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "zono-fe-staging"
          directory: "./.next"
          branch: dev
          gitHubToken: ${{ secrets.GH_PAT }}